name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.war staging
      - name: List files in the repository
        run: |
          pwd
          ls -l
          ls -l staging
      - uses: actions/upload-artifact@v2
        with:
         name: SreeJavaExample.war
         path: staging
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'SreeJavaExample.war'
          path: staging

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Deploy to tomcat
        run: curl -T staging/SreeJavaExample.war "http://tomcat:s3cret@34.200.241.212:8080/manager/text/deploy?path=/sree&update=true"
